spring:
  application:
    name: study_webflux
  r2dbc:
    url: r2dbc:mysql://localhost:3306/spring
    username: qwer
    password: asdf
  data:
    redis:
      host: 127.0.0.1
      port: 6379

logging:
  level:
    root: INFO
    org:
      springframework:
        r2dbc: DEBUG